**A**

In [1]:
#a)
def GE(A,b):
    n = len(A)
    U=A.copy()
    L=[[0]*n for i in range(n)]
    for i in range(n):
        L[i][i]= 1
    for i in range(n):
        aii = U[i][i]
        for j in range(i+1,n):
            aji = U[j][i]
            L[j][i] = aji/aii
            for k in range(n):
                U[j][k] = -U[i][k]*aji/aii+U[j][k]
    #forwardsolve Ly=b
    y=[0]*n
    for i in range(n):
        y[i] = b[i]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
            
    #backward solve Ux = y
    x=[0]*n
    for i in range(n-1,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - U[i][j]*x[j]
        x[i] = x[i]/U[i][i]
        
    return [x,L,U]

**B**

In [11]:
#b)
import scipy.linalg as l
import numpy as np
h = l.hilbert(10)
z = np.ones((10,1))
b=np.matmul(h,z)

**L MATRIX**

In [12]:
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)},linewidth=np.inf)
np.array(GE(h,b)[1])

array([[1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.500, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.333, 1.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.250, 0.900, 1.500, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.200, 0.800, 1.714, 2.000, 1.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.167, 0.714, 1.786, 2.778, 2.500, 1.000, 0.000, 0.000, 0.000, 0.000],
       [0.143, 0.643, 1.786, 3.333, 4.091, 3.000, 1.000, 0.000, 0.000, 0.000],
       [0.125, 0.583, 1.750, 3.712, 5.568, 5.654, 3.500, 1.000, 0.000, 0.000],
       [0.111, 0.533, 1.697, 3.960, 6.853, 8.615, 7.467, 4.000, 1.000, 0.000],
       [0.100, 0.491, 1.636, 4.112, 7.930, 11.631, 12.600, 9.529, 4.500, 1.000]])

**U MATRIX**

In [13]:
np.array(GE(h,b)[2])

array([[1.000, 0.500, 0.333, 0.250, 0.200, 0.167, 0.143, 0.125, 0.111, 0.100],
       [0.000, 0.083, 0.083, 0.075, 0.067, 0.060, 0.054, 0.049, 0.044, 0.041],
       [0.000, 0.000, 0.006, 0.008, 0.010, 0.010, 0.010, 0.010, 0.009, 0.009],
       [0.000, 0.000, 0.000, 0.000, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, -0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, -0.000, 0.000, -0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000],
       [0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000, 0.000]])

**x**

In [14]:
np.set_printoptions(precision=15)
np.array(GE(h,b)[0])

array([[1.000000000438575],
       [0.999999962349414],
       [1.00000079744797 ],
       [0.999992785418523],
       [1.000034268596861],
       [0.999906137184279],
       [1.000153512202063],
       [0.999852062168331],
       [1.000077474058709],
       [0.999982999849781]])